services:
  - type: web
    name: ams2-backend
    env: java
    plan: free
    rootDir: backend-java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/ams2-backend-1.0.0.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://shortline.proxy.rlwy.net:20586/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: AiadDNdnGEzrVqTaDMfmTqeSoekcLQyV
      - key: JAVA_VERSION
        value: 21